// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg5jL7XOLk4lWa11iYSHeCHp1GUfNHFto',
    appId: '1:95701884075:web:9ed72040685f4562842bee',
    messagingSenderId: '95701884075',
    projectId: 'educart-257c8',
    authDomain: 'educart-257c8.firebaseapp.com',
    storageBucket: 'educart-257c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLe1g6s47Jeyo3Z0JCQE6OXZIHoRFsds',
    appId: '1:95701884075:android:33bcbaf831c9b63e842bee',
    messagingSenderId: '95701884075',
    projectId: 'educart-257c8',
    storageBucket: 'educart-257c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABE68OrV-b7X5QrA3em7BDm1xjflmxktM',
    appId: '1:95701884075:ios:f36efb20f8e3480b842bee',
    messagingSenderId: '95701884075',
    projectId: 'educart-257c8',
    storageBucket: 'educart-257c8.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABE68OrV-b7X5QrA3em7BDm1xjflmxktM',
    appId: '1:95701884075:ios:f36efb20f8e3480b842bee',
    messagingSenderId: '95701884075',
    projectId: 'educart-257c8',
    storageBucket: 'educart-257c8.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg5jL7XOLk4lWa11iYSHeCHp1GUfNHFto',
    appId: '1:95701884075:web:c3ffa2f491d1630e842bee',
    messagingSenderId: '95701884075',
    projectId: 'educart-257c8',
    authDomain: 'educart-257c8.firebaseapp.com',
    storageBucket: 'educart-257c8.firebasestorage.app',
  );
}
